# Generated by Django 4.1.6 on 2023-11-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0003_users_delete_blog_delete_pengguna'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
    ]
