# Generated by Django 4.1.6 on 2023-11-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0005_courses_karakteristik_review_sertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='karakteristik_id',
            field=models.CharField(default='1,2', max_length=200),
        ),
    ]
