# Generated by Django 4.1.6 on 2023-11-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0006_courses_karakteristik_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertificate',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
