# Generated by Django 4.1.6 on 2023-11-28 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0007_sertificate_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sertificate',
            new_name='Certificate',
        ),
    ]
