# Generated by Django 4.1.6 on 2023-11-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0008_rename_sertificate_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(default='Belum Selesai', max_length=200),
        ),
    ]
