# Generated by Django 4.1.6 on 2023-11-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0010_courses_link_continue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='link_continue',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='link_image',
        ),
    ]
